#!/bin/bash
    echo "Removing conflicting symbolic link."
   sudo rm -f etc/nginx/sites-enabled/default
sudo ln -s etc/nginx/sites-enabled etc/nginx/sites-available/default .
 sudo grep -q "listen 80;" etc/nginx/sites-available/default .
    echo "Updating Nginx configuration to listen on port 80..."
    sudo sed -i 's/listen 8080;/listen 80;/' etc/nginx/sites-available/default .
