#!/usr/bin/env bash
    echo "Removing conflicting symbolic link."
    rm -f etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
    echo "Updating Nginx configuration to listen on port 80..."
     sed -i 's/listen 8080;/listen 80;/' /etc/nginx/sites-available/default
